1단계 - 예약 기능 구현
next-step/spring-roomescape-reservation pull request #58
Opened 2024-06-06 10:01 UTC by OikimiO

안녕하세요ㅎ

이번 사전 학습을 진행하는 목표 중 하나로 테스트 코드로 문서화를 진행했습니다.
그래서 완벽하지 않은 상태에서 제 개인적인 기준..^^ BDD 관점의 테스트 코드를 만들어 보려 노력했습니다. 
그런데 테스트를 진행하며 각각의 테스트를 진행하면서는 문제 없었던 것들이.. 통합테스트를 하며 문제가 발생했습니다.

문제가 발생한 원인은 테스트 코드간의 의존성이 생겨.. 데이터를 저장하지 않아야할 사항에 저장이 된 상태로 테스트가 진행되거나 하는.. 문제가 
있었습니다..;;ㅎ
제가 알기로도 테스트 코드간의 의존성은 생겨선 안되고 독립적으로 구성이되어야 하는데.. 현재는 그렇지 못하다는 한계가 존재합니다..ㅎ

테스트 코드가 미완성인 상태로 코드를 올립니다.. 혹시나 코드를 보시고 테스트의 방향성이나 고쳐야 할 부분들이 있다면 알려주시면 감사하겠습니다.

2024-06-07 14:59 UTC, xrabcde requested changes
안녕하세요 은호님 ~ 첫 번째 미션 리뷰를 맡은 조아라입니다 ☺️
요구사항에 맞게 잘 구현해주셨네요 ㅎㅎ
몇 가지 코멘트 남겨드렸는데 확인부탁드립니다 !
어렵거나 고민되는 점이 있다면 편하게 질문 남겨주세요 ~

2024-06-07 14:59 UTC, xrabcde commented on src/main/java/roomescape/admin/controller/AdminController.java
> +    private AdminService adminService;
의존성을 필드로 주입해주고 계시네요! 
이 방법은 어떤 식으로 동작하며 어떤 장단점이 있을까요? 

[Spring의 다양한 의존성 주입방법](https://tecoble.techcourse.co.kr/post/2020-07-18-di-constuctor-injection/)에 대해 학습해보시면 좋을 것 같습니다 ㅎㅎ

2024-06-07 14:59 UTC, xrabcde commented on src/main/java/roomescape/admin/controller/AdminController.java
> +public class AdminController {
한 컨트롤러에서 너무 많은 일을 해주고 있어요 😢
공통점이 있는 api끼리 컨트롤러를 분리해보는 것은 어떨까요?

2024-06-07 14:59 UTC, xrabcde commented on src/main/java/roomescape/admin/dto/ReadReservationResponse.java
> +    }
정적 팩토리 메서드를 사용해주셨군요 ! 
[정적 팩토리 메서드 네이밍 컨벤션](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90#%EC%A0%95%EC%A0%81_%ED%8C%A9%ED%86%A0%EB%A6%AC_%EB%A9%94%EC%84%9C%EB%93%9C_%EB%84%A4%EC%9D%B4%EB%B0%8D_%EA%B7%9C%EC%B9%99)에 대해서도 한 번 읽어보시면 좋을 것 같습니다 ☺️

2024-06-07 14:59 UTC, xrabcde commented on src/main/java/roomescape/admin/repository/AdminRepository.java
> +        return id;
변수 할당하지 않고 즉시 return 해줄 수 있겠네용

2024-06-07 14:59 UTC, xrabcde commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +    @DisplayName("방탈출 예약은")
Nested 와 DisplayName 활용 👍👍

2024-06-07 14:59 UTC, xrabcde commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +    class Describe_Resevation{
🤓

```suggestion
    class Describe_Reservation{
```

2024-06-07 14:59 UTC, xrabcde commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +
이 테스트코드는 왜 주석처리 해두신건가요!! 사용하지 않는다면 삭제해주세요 ㅎㅎ

2024-06-07 14:59 UTC, xrabcde commented on src/main/java/roomescape/admin/controller/AdminController.java
> +    @GetMapping(BASE_PATH+"/time")
페이지 호출이 안되고 있는 것 같아요 ~ (호출 path를 확인해주세요 😉)

<img width="650" alt="image" src="https://github.com/next-step/spring-roomescape-reservation/assets/56033755/70396c34-f9ab-4933-a61d-30c8b2cf6d84">

2024-06-07 14:59 UTC, xrabcde commented on src/main/java/roomescape/admin/entity/Reservation.java
> +        }
Reservation 의 관점에서 read 는 어떤 역할인건가요? 
ResultSet 을 Reservation 으로 변환하는 건 누구의 책임일까요? 
`조회` 라는 행위에 대해 더 고민해보시면 좋을 것 같습니다 !

2024-06-07 14:59 UTC, xrabcde commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +            assertThat(reservations.size()).isGreaterThan(0);
`isPositive()` 를 사용할 수 있을 것 같아요 

```suggestion
            assertThat(reservations.size()).isPositive();
```

2024-06-07 14:59 UTC, xrabcde commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +            assertThat(reservations.size()).isEqualTo(2);
`hasSize()` 를 사용할 수 있을 것 같아요 ~ 

```suggestion
            assertThat(reservations).hasSize(2);
```

2024-06-08 00:47 UTC, OikimiO commented on src/main/java/roomescape/admin/controller/AdminController.java
> +    private AdminService adminService;
장점
1. 코드가 간결
2. 본인이 아닌 DI Container가 의존성을 관리해 객체간의 결합도가 낮아짐 

단점
1. 무분별한 필드 주입으로 단일 책임 원칙이 깨질 수 있음
2. DI Container가 의존성을 관리해, DI Container가 아닌 환경에선 사용하기 어려움
3. field injection은 Reflection으로 주입받아 불변성을 보장할 수 없음
4. RunTime 환경에서 순환 의존이 발생하는 것을 알 수 있다는 단점이 있음

2024-06-08 00:51 UTC, OikimiO commented on src/main/java/roomescape/admin/controller/AdminController.java
> +public class AdminController {
다음과 같이 구성 하려는데, 혹시 괜찮을까요? ㅎ

AS_IS: AdminController
TO_BE: ReservationController, ReservationTimeController

2024-06-08 01:08 UTC, OikimiO commented on src/main/java/roomescape/admin/dto/ReadReservationResponse.java
> +    }
네이밍 컨벤션을 다음과 같이 변경하겠습니다 ㅎ

변경 원인
 - 개발자가 임의로 만든 메서드명은 파악의 어려움

AS_IS > TO_BE
1. entityToDTO > from
2. entityToList > of
3. read > from

2024-06-08 01:09 UTC, OikimiO commented on src/main/java/roomescape/admin/repository/AdminRepository.java
> +        return id;
참고하겠습니다ㅎ

2024-06-08 01:18 UTC, OikimiO commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +
넵넵 참고하겠습니다..! ㅎ

2024-06-08 06:50 UTC, OikimiO commented on src/main/java/roomescape/admin/entity/Reservation.java
> +        }
데이터 액세스 계층의 역할
   1. DB 접근에 대한 추상화
   2. CRUD관련 메서드 제공
   3. DB의 데이터를 애플리케이션의 객체로 매핑
   4. 트랜잭션 관리

도메인 계층의 역할
   1. 비지니스 규칙과 로직을 표현
   2. 도메인 모델간의 엔티티 관계 표현
   3. 시스템의 주요 구조와 설계를 결정하는 역할

Reservation의 관점에서의 read

- 도메인 계층에서 데이터 매핑을 하고 있음
- 이는 도메인 계층과 액세스 계층의 결합도를 높이게 됨

ResultSet을 Reservation으로 변환하는 책임은?
 - 데이터 매핑을 담당하는 Data Access 계층의 책임
 
해당 내용을 토대로 코드를 수정해보도록 하겠습니다. 
예리한 답변 감사합니다 ㅎ

2024-06-08 06:50 UTC, OikimiO commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +            assertThat(reservations.size()).isEqualTo(2);
isEqualTo를 사용하지 않고 hasSize를 사용하는게 더 명확하고 간단하네요..!
참고하겠습니다ㅎ

2024-06-09 11:42 UTC, xrabcde approved these changes
안녕하세요 은호님 ~ 피드백 내용을 잘 반영해주셨네요 ㅎㅎ
이어서 2단계 진행해주시면 되겠습니다 ~!

2024-06-09 11:42 UTC, xrabcde commented on src/main/java/roomescape/admin/controller/ReservationController.java
> +    }
화면 응답용 컨트롤러와 api 응답용 컨트롤러를 나눠보는 건 어떤가요?

2024-06-09 11:42 UTC, xrabcde commented on src/main/java/roomescape/admin/controller/ReservationController.java
> +        List<ReadReservationResponse> response = this.reservationService.readReservation();
`readReservation()` 은 단건 조회와 헷갈릴 수 있어서 (이번 요구사항에는 없지만)
목록 조회라는 내용이 더 드러나는 네이밍을 지어줘도 좋을 것 같아요 ㅎㅎ

2024-06-09 11:42 UTC, xrabcde commented on src/main/java/roomescape/admin/dto/ReadReservationResponse.java
> +    public static ReadReservationResponse from(Reservation reservation){
👍👍

2024-06-09 11:42 UTC, xrabcde commented on src/main/java/roomescape/admin/repository/ReservationTimeRepository.java
> +        return this.jdbcTemplate.query(ReservationTimeQuery.READ_ALL, readReservationTimeRowMapper());
여기도 여러건을 조회한다는 내용이 이름에 들어갈 수 있을 것 같아요 ㅎㅎ

2024-06-09 11:42 UTC, xrabcde commented on src/main/java/roomescape/admin/service/ReservationTimeService.java
> +    private final ReservationTimeRepository reservationTimeRepository;
서비스를 분리하니 훨씬 책임과 역할이 명확해진 것 같아요 👍

2024-06-09 11:42 UTC, xrabcde commented on src/main/resources/schema.sql
> +    FOREIGN KEY (time_id) REFERENCES reservation_time (id) -- 외래키 추가
외래키를 사용해주셨군요 !
시간에 대한 예약이 존재하는 상황에서 시간을 삭제하려고 하면 어떻게 될까요? 🤔
2단계 예외처리 진행하시면서 같이 해결해볼 수 있을 것 같아요 ㅎㅎ

2024-06-09 11:42 UTC, xrabcde commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +public class AdminControllerTest {
테스트 코드도 운영코드에 맞춰 클래스 분리가 필요하겠네요 ~!

2024-06-09 11:42 UTC, merged

2024-06-10 09:01 UTC, OikimiO commented on src/main/java/roomescape/admin/controller/ReservationController.java
> +        List<ReadReservationResponse> response = this.reservationService.readReservation();
쿼리 메서드 명명 규칙을 참고하여 구성을 변경했습니다. 
조회를 변경하면서 삭제/저장 메서드도 변경했습니다 ㅎ

AS_IS > TO_BE
 - DTO read~: find~
 - <List> read~: findAll
 - DTO save ~: save
 - void delet ~: delete

2024-06-10 09:02 UTC, OikimiO commented on src/test/java/roomescape/admin/controller/AdminControllerTest.java
> +public class AdminControllerTest {
2단계에선 참고하여 진행하겠습니다
감사합니다 ㅎ