1단계 - 예약 기능 구현
next-step/spring-roomescape-reservation pull request #66
Opened 2024-06-08 12:44 UTC by dharana77

안녕하세요! 1단계 예약기능 구현입니다.

잘부탁드립니다 🙇 🙇‍♂️

2024-06-09 07:59 UTC, pkeugine requested changes
안녕하세요 진영님!
리뷰를 맡게 된 박유진입니다.
앞으로 함께 다양한 걸 시도해보고, 둘 다 많이 배우길 바라요.

작업해주신 부분에 대한 리뷰를 몇 가지 남겼는데요,
간단한 것부터 자잘한 버그 수정까지 골고루 있네요!

만약 바쁘시다면 일단 버그부터 수정한 뒤 다시 리뷰 요청 주시면 좋을 것 같아요.
다른 리뷰는 다음 step 을 진행하면서도 적용할 수 있으니까요.

주말에도 정말 고생많으십니다!
남은 일요일 알차게 보내보아요 :) 💪 💪 💪

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/reservation/data/ReservationAddRequestDTO.java
> +public class ReservationAddRequestDTO {
클래스명, 변수명, 그리고 메서드명을 지을 때 `DTO` 와 같은 이름은 어떻게 적으면 좋을까요?
많은 개발자 / 팀이 적용하는 [Google 의 자바 컨벤션](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)이 있는데요,
한 번 확인해보고 진영님의 프로젝트에도 반영해보면 좋을 것 같아요.

이런 이름 외에도 공백이나 import 문 등 다양한 요소에 대한 컨벤션이 있으니 꼭 확인해보는걸 추천드려요!

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/reservation/ReservationController.java
> +    }
`@Autowired` 어노테이션을 사용해주셨군요!
이 어노테이션은 필드, 생성자 등 붙일 수 있는 곳이 여러 개 있죠.
그 중 생성자는 꼭 붙이지 않아도 빈 주입이 되는데요, 필수로 붙일 필요가 없다면 제거해보는건 어떨까요?

```suggestion
    public ReservationController(ReservationService reservationService) {
        this.reservationService = reservationService;
    }
```

2024-06-09 07:59 UTC, pkeugine commented on src/main/resources/application.properties
> +        mode: always
`application.properties` 파일에 `properties` 방식과 `yml` 방식이 섞여서 사용되고 있어요.
둘 중 어떤 방식을 사용하고 싶은지 정하고 파일을 `yml` 로 바꾸거나 `properties` 방식으로 설정을 다시 작성해보면 좋을 것 같아요.

2024-06-09 07:59 UTC, pkeugine commented on src/main/resources/application.properties
> +        mode: always
만들어주신 파일들 중 일부에서 다음과 같은 표시가 보여요: 
<img width="171" alt="Screenshot 2024-06-09 at 3 59 25 PM" src="https://github.com/next-step/spring-roomescape-reservation/assets/48251668/98baa27b-ad74-446b-a5fd-745d79c15b60">

이는 파일 끝부분에 empty line 이 없어서 그런건데요,
왜 empty line 이 필요한지 알아보고, 없는 곳에 하나씩 추가해보죠!

참고로 intelliJ 설정에서 파일 끝에 자동으로 empty line 을 추가해주는 옵션을 활성화하면 꽤 유용해요!
<img width="1094" alt="Screenshot 2024-06-08 at 2 05 28 PM" src="https://github.com/next-step/spring-roomescape-reservation/assets/48251668/42878806-ef5d-45b4-bf82-c6c02e59a333">

2024-06-09 07:59 UTC, pkeugine commented on src/main/resources/static/js/reservation-legacy.js
> +
불필요한 공백은 지워주도록 하죠!

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/theme/ThemeController.java
> +}
테마쪽 Controller 를 만드시면서 뭔가 빠진게 있는 것 같아요!
실제로 테마 생성을 하려고 하면 404 응답이 내려오네요.
수정해보죠 :)
<img width="884" alt="Screenshot 2024-06-09 at 4 05 32 PM" src="https://github.com/next-step/spring-roomescape-reservation/assets/48251668/fdcac3f9-3a1f-46f8-bf0e-e1ba8cd06861">

2024-06-09 07:59 UTC, pkeugine commented on src/main/resources/templates/admin/time.html
> +        <a class="nav-link" href="/admin/time">Time</a>
백엔드 부분은 아니지만 프로젝트의 완성도를 위해 '시간 관리 페이지' 의 버튼 이름을 바꿔보는건 어떨까요?
시간을 추가하는 기능인데 '예약 추가' 라고 나타나고 있어요 :

<img width="1295" alt="Screenshot 2024-06-09 at 4 09 17 PM" src="https://github.com/next-step/spring-roomescape-reservation/assets/48251668/580e0e74-b805-4bc4-b703-52472043e41e">

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/entities/Reservation.java
> +    }
도메인이 영속화 되기 전에는 id 가 없고
영속화 된 이후에는 id 가 있기 때문에 `setId` 가 만들어졌죠?
그런데 id 와 같은 중요한 정보를 쉽게 변경할 수 있게 해주는 이 메서드는 만들어 사용하기엔 조금 위험한 것 같아요.
id 를 넣어줄 때는 생성자를 이용하여 넣도록 해보는건 어떨까요?

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/repositories/ReservationRepository.java
> +                "on r.time_id = t.id\n";
`multi line string` 을 이용하여 쿼리를 관리해보는건 어떨까요?

(+) SELECT & FROM 을 전체 대문자로 만들어서 작성해주셨는데요, 다른 sql 키워드도 같은 방식으로 작성해보면 좋을 것 같아요!

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/reservation/ReservationController.java
> +@RequestMapping("/reservations")
`@RestController` 와 `@RequestMapping` 👍 
공통으로 들어가는 url 부분도 깔끔하게 분리해주셨네요!

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/repositories/ReservationRepository.java
> +    }
Reservation 객체를 생성해주는 부분을 람다 형식으로 바꿔보는건 어떨까요?
그리고 지역변수를 선언할 필요 없이 바로 return 할 수도 있을 것 같네요!

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/entities/ReservationTime.java
> +
여기도 불필요한 공백이 있어요! 👀

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/entities/Reservation.java
> +package roomescape.entities;
패키지 구조에서 `entities` 와 각종 domain (reservation, reservationtime, theme) 을 분리해주신 이유가 궁금해요!

2024-06-09 07:59 UTC, pkeugine commented on build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:5.3.1'
중복되는 부분이 몇 개 보이네요!
깔끔하게 중복이 없도록 해볼까요? :)

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/entities/Reservation.java
> +    }
이 생성자로 인해 도메인이 dto 에 의존하게 되었어요.
dto 에서 이 작업을 하도록 해보면 어떨까요?

저는 도메인은 웬만하면 다른 도메인이 아닌 존재에 의존하지 않도록 하는데요,
왜 그럴지 한 번 생각해보는 것도 재밌을 것 같아요 :)

2024-06-09 07:59 UTC, pkeugine commented on src/main/java/roomescape/reservationTime/ReservationTimeController.java
> +        return reservationTime;
`ResponseEntity` 라는 클래스에 대해 알아보고, 이를 활용해보는건 어떨까요?
api 가 내려주는 응답을 훨씬 편리하게 관리할 수 있다는 장점이 있거든요.

2024-06-09 07:59 UTC, pkeugine commented on build.gradle
만들어주신 기능에 대한 테스트를 한 번 만들어보는걸 추천드려요!
그리고 기존에 있던 테스트 중 하나가 현재 실패하고 있어요: 
<img width="879" alt="Screenshot 2024-06-09 at 4 38 05 PM" src="https://github.com/next-step/spring-roomescape-reservation/assets/48251668/82263220-7e65-4a47-9d3c-12e6fa1f5baf">

이 테스트가 다시 정상 작동하도록 변경해보죠!

2024-06-13 21:04 UTC, dharana77 commented on src/main/java/roomescape/entities/Reservation.java
> +package roomescape.entities;
이건 이전 회사에 다닐때 사용했던 방식을 사용해보려고 했었는데요!
kotlin/spring을 사용하긴 했었는데 보통은 controller, service, repository, entity ... 와 같은 구조를 사용했었는데 
해당 회사에서 도메인 별로 분리하여 도메인 별로 해당 레이어들을 추후 사용해 높은 구조를 사용해보았을때 
결합도나 유지보수 편리성에서 좋았던 경험이 있어서 해당 구조에 대해 어떻게 생각하시나 궁금한점이 있었습니다!
저도 이렇게 되어 있는 것의 정확한 원인은 알지 못했었는데 추후 도메인 별로 분리를 쉽게 하게 하려고 하거나 유지보수의 편리성 때문에 한게 아닐까 추측해서 사용해보았습니다!

유진님께서는 해당 구조에 대해 어떻게 생각하시는지도 궁금합니다.

2024-06-16 18:06 UTC, dharana77 commented
안녕하세요! 한주 잘보내셨나요?
다른 작업때문에 진도가 약간 느렸지만 앞으로 더 힘내서 열심히 해보겠습니다!

말씀해주신 사항들이 굉장히 도움이 많이 됐고 그 중 일부를 반영해보았는데요,
아직 dto의존성 부분과 테마 오류 수정 부분, Reservation 객체 등을 빌드 타입으로 리턴 부분은 수정하지못했습니다 🥲 

그래도 피드백이 빠른게 더 좋을 것 같아 우선 해당 부분까지 수정하고 다음 단계 내용과 함께 해당 내용 반영하겠습니다. 🙇‍♂️ 

또 궁금한 사항이 있어 하나 질문드렸는데요! 유진님께서는 어떻게 생각하시는지 궁금해서 질문드렸습니다!
감사합니다. 오늘도 좋은 하루 되세요 :)
https://github.com/next-step/spring-roomescape-reservation/pull/66#discussion_r1638948764

2024-06-17 17:18 UTC, pkeugine commented on src/main/java/roomescape/entities/Reservation.java
> +package roomescape.entities;
괜찮다고 생각해요!
다만 레이어 (repository, domain, entity, service, controller...) 또는 도메인 (reservation, reservationtime, theme...) 중 하나를 기준으로 나누면 찾을 때 비교적 덜 헷갈릴 것 같아요. 그리고 의존도 관리를 잘 했다는 가정하에 모듈을 분리한다거나, 세부 프로젝트로 나누어 관리한다던지, 유지보수할 때 조금 더 수월할 것 같네요. 저는 "제가 원하는 로직을 바로 찾을 수 있는 구조"를 제일 선호해요. 매일같이 유지보수할 때 제일 와닿는 요소거든요!

패키지 구조는 사실 같은 사람이라도 본인이 어떤 경험을 했는지에 따라, 그리고 어떤 프로젝트를 관리하는가에 따라 매번 생각이 바뀌는 주제이기도 해요. 이 프로젝트를 관리해보면서 진영님이 생각했을 때 '방탈출 예약 관리' 서비스에 맞는 구조를 만들어가보면 좋을 것 같네요. :)

2024-06-17 17:34 UTC, pkeugine approved these changes
안녕하세요 진영님!
미션 꾸준히 진행하시느라 정말 고생 많으십니다...
말해주신 것처럼 일단 적용하신 리뷰 중심으로 확인했고,
몇 가지 소소한 리뷰 추가로 남겨봤어요.
다음 단계 진행하시면서 한 번 반영해봐도 괜찮을 것 같네요.
일단 이번 스텝은 여기서 머지하고, 리뷰 제가 기억해두었다가 다음 스텝 진행하면서 함께 확인해볼게요.
다음 스텝도 파이팅입니다!!!! 🔥 🔥 🔥

2024-06-17 17:34 UTC, pkeugine commented on src/test/java/roomescape/MissionStepTest.java
> +        Map<String, String> timeParams = new HashMap<>();
이번에 변경해주신 내용이 아니긴하지만, JUnit5 는 테스트 클래스의 접근제한자를 public 으로 강제하지 않아요.
그러니 public 부분을 제거해보는건 어떨까요? 불필요하다면 꼭 넣을 필요는 없으니까요 :)
이 참에 테스트에서 사용하시는 JUnit5 와 RestAssured 의 기능을 한 번 알아보는 것도 재밌겠네요.

2024-06-17 17:34 UTC, pkeugine commented on src/test/java/roomescape/MissionStepTest.java
> +        timeParams.put("time", "15:40");
`ReservationTimeAddRequestDto` 를 테스트에서 사용해보는건 어떨까요?
Map 대신 직접 만든 dto 를 사용하는거죠!

2024-06-17 17:34 UTC, pkeugine commented on src/main/resources/templates/admin/theme.html
> +</html>
백엔드 관련 코드는 아니긴하지만, 여기 아직 empty line 이 추가되어 있지 않네요.
프론트엔드 파일 전체적으로 한 번 확인해주세요!

2024-06-17 17:34 UTC, pkeugine commented on src/main/java/roomescape/theme/ThemeService.java
> +
불필요한 공백이 아직 다 제거되지 않았어요!

2024-06-17 17:34 UTC, pkeugine commented on src/main/java/roomescape/reservationTime/ReservationTimeController.java
> +package roomescape.reservationTime;
dto 이름을 컨벤션에 맞게 잘 바꾸어주셨으니, package 명도 한 번 확인해볼까요?
보통 패키지명은 lowerCamelCase 를 사용하지 않거든요.
제가 이전 리뷰에 남겼던 google convention 링크에도 해당 부분이 있습니다 :)

2024-06-17 17:34 UTC, pkeugine commented on src/main/java/roomescape/reservation/ReservationController.java
> +        List<Reservation> res = reservationService.searchAllReservations();
줄임말은 최대한 지양해보도록 해보아요.
분명 이를 더 잘 나타내는 이름이 있을거예요.

2024-06-17 17:34 UTC, pkeugine commented on src/main/java/roomescape/reservation/ReservationController.java
> +        return ResponseEntity.ok().body(reservation);
`ResponseEntity` 👍

2024-06-17 17:34 UTC, pkeugine commented on src/main/java/roomescape/reservationTime/ReservationTimeService.java
> +    }
비슷한 역할을 하는 메서드끼리 모아두면 어떨까요?
예를 들어 `searchAllTimes` 와 `findByTime` 은 둘 다 ReservationTime 을 조회한다는 공통점이 있어요.
(search 와 find 중 표현을 하나로 통일해보는 것도 좋을 것 같은데, 이건 고민해보시고 적용하지 않아도 괜찮아요)

2024-06-17 17:35 UTC, merged

2024-06-20 14:07 UTC, dharana77 commented on src/main/java/roomescape/entities/Reservation.java
> +    }
해당 부분에서 저는 dto의 변경으로 인한 내용을 도메인에 영향이 가지 않게 하기 위해서 라는 결론을 내렸는데요,
혹시 해당 부분 말고 다른 이유가 있다고 생각하시는지, 그리고 위에 제가 결론지은 내용이 맞다고 생각하시는지 궁금합니다! 🤔