🚀 1단계 - 예약 기능 구현(1-3단계 - 시간 관리 기능 추가)
next-step/spring-roomescape-reservation pull request #81
Opened 2024-06-11 09:46 UTC by gomshiki

1-3 단계 미션 구현 완료하여 PR 드립니다.
감사합니다.!

2024-06-13 08:04 UTC, Hyeon9mak requested changes
안녕하세요 준성님! 예약기능 구현도 잘 해주셨습니다.
몇 가지 코멘트 남겼으니 확인해주세요!

2024-06-13 08:04 UTC, Hyeon9mak commented on src/main/java/roomescape/reservationTime/ReservationTime.java
> +    }
getter 와 생성자들의 순서를 정리해주면 가독성이 더욱 올라갈 것 같아요!

2024-06-13 08:04 UTC, Hyeon9mak commented on src/main/java/roomescape/reservationTime/ReservationTimeRequestDto.java
> +
마찬가지로 멤버변수, 생성자, getter 순서를 정리해보는 건 어떨까요?

2024-06-13 08:04 UTC, Hyeon9mak commented on src/main/java/roomescape/reservation/Reservation.java
생성자 체이닝을 활용하는 것도 좋은 방법일 것 같아요 😄 

```java
 public Reservation(String name, String date, ReservationTime reservationTime) {
      this(null, name, date, reservationTime);
  }
```

2024-06-13 08:04 UTC, Hyeon9mak commented on src/main/java/roomescape/reservation/ReservationRepository.java
java 17 버전 이상을 사용중인 프로젝트네요~

```java
        final String sql = """
                    SELECT r.id as reservation_id,
                    r.name as reservation_name, 
                    r.date as reservation_date, 
                    t.id as time_id, 
                    t.start_at as start_at 
                    FROM reservation as r
                    inner join reservation_time as t
                    on r.time_id = t.id;
                """;

```

2024-06-13 08:04 UTC, Hyeon9mak commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +                "PRIMARY KEY (id))");  // 외래키 제거
테스트코드 쪽에만 별도로 FK 를 제거하신 이유가 있을까요?

2024-06-13 11:49 UTC, gomshiki commented on src/test/java/roomescape/reservation/ReservationControllerTest.java
> +                "PRIMARY KEY (id))");  // 외래키 제거
잠시 제가 미쳤었나봐요... 제가 왜 저렇게 작성했는지 모르겠네요 :( 
FK 추가되는게 맞는데 해당 부분은 무시해주시면 감사하겠습니다 ㅎㅎ;;

2024-06-14 09:16 UTC, Hyeon9mak approved these changes
안녕하세요 준성님! 피드백 잘 반영해주셨습니다!
다음 단계로 넘어가시죠 😄

2024-06-14 09:16 UTC, Hyeon9mak commented on src/main/java/roomescape/reservation/ReservationRepository.java
> +                       r.name as reservation_name,
😉 👍

2024-06-14 09:16 UTC, merged